const GET_LIST_OF_POSTS = 'GET_LIST_OF_POSTS';
const CREATE_POST = 'CREATE_POST';
const UPDATE_POST = 'UPDATE_POST';
const DELETE_POST = 'DELETE_POST';

export default {
    GET_LIST_OF_POSTS,
    CREATE_POST,
    UPDATE_POST,
    DELETE_POST
};