const GET_LIST_OF_POSTS = 'GET_LIST_OF_POSTS';
const CREATE_POST = 'CREATE_POST';
const UPDATE_POST = 'UPDATE_POST';
const DELETE_POST = 'DELETE_POST';
const SORT_POSTS_BY_TYPE = 'SORT_POSTS_BY_TYPE';
const FILTER_POSTS_BY_TYPE_WITH_VALUE = 'FILTER_POSTS_BY_TYPE_WITH_VALUE';

export default {
    GET_LIST_OF_POSTS,
    CREATE_POST,
    UPDATE_POST,
    DELETE_POST,
    SORT_POSTS_BY_TYPE,
    FILTER_POSTS_BY_TYPE_WITH_VALUE
};